server: 
  port: 53030
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:53000/eureka/
        register-with-eureka: false   #禁用客户端注册行为 注册时删掉此行
        fetch-registry: false     #禁用客户端注册行为 注册时删掉此行

spring:
##################### DB #####################
  datasource: 
    url: jdbc:mysql://localhost:3306/micro-program?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root

    ##################### redis #####################
  redis:
    #cluster:
    #max-redirects: ''   # （普通集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。
    #nodes: ''  # （普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
    database: 0   # 连接工厂使用的数据库索引
    host: 127.0.0.1
    password: foobared123
    port: 6379
    pool:
      maxActive: 5000  # 池在给定时间可以分配的最大连接数。使用负值无限制。
      maxIdle: 5000    # 池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
      maxWait: 10000   # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
      minIdle: 10    # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
      #sentinel:
      #master: ''    # （哨兵模式，不使用则不用开启）Redis服务器的名称。
      #nodes: ''     # （哨兵模式，不使用则不用开启）主机：端口对的逗号分隔列表。
    ssl: false       # 启用SSL支持
    timeout: 60000       # 以毫秒为单位的连接超时。

            
logging: 
  config: classpath:log4j2-dev.xml
  
swagger: 
  enable: true


